name: Docker Testing

on:
  pull_request:
    # paths:
    #   - 'infra/*'

jobs:
  docker-testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Ubuntu Version
        run: cat /etc/os-release

      - name: Docker Version
        run: docker version

      - name: Docker Compose Build
        run: docker-compose build
